#working directory
#workdir: "/mnt/f/Data/Encode_annotation/all/encode_raw"
workdir: "/mnt/c/Users/Haoyu/Desktop/snake_test"
#gtf_dir: "/mnt/f/Data/Encode_annotation/all/encode_raw"
gtf_dir: "/mnt/c/Users/Haoyu/Desktop/snake_test"
target_genes: "/mnt/c/Users/Haoyu/Desktop/test_gene_list.txt"



reference_annotation: "/mnt/e/reference_for_APTARS/gencode.v29.short.gtf"

reference_genome: "/mnt/e/reference_for_APTARS/hg38.fa"
metadata: "/mnt/e/Encode_tsv/Metadata/lung.tsv"
quanti_file_path: "/mnt/e/Encode_tsv/all"



# threads
threads: 1


