# working directory 
workdir: ""

# The directory storing ENCODE annotation files
gtf_dir: ""

# The file with names of genes of interest
target_genes: ""


#reference GENCODE annotation
reference_annotation: ""

# reference genome hg38.fa
reference_genome: ""

# Metadata from ENCODE, with experimental accessions and file names
metadata: ""

# Directory stores quantification tsv files from ENCODE
quanti_file_path: ""



# threads
threads: 4


