name: encode_gene_search
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - snakemake==8.2.3
 - biopython==1.79
 - gffread==0.12.7
 - r-base=4.3.2
 - r-devtools
 - r-tidyverse
 - r-dplyr=1.1.4
 - r-ggplot2=3.4.4
 - r-cowplot=1.1.3
 - r-data.table=1.14.10
 - r-rcolorbrewer=1.1_3
 - r-reshape2
 - bioconductor-genomeinfodbdata
 - bioconductor-rtracklayer
 - bioconductor-orfik
 - bioconductor-genomicfeatures
 - bioconductor-genomicranges
 - bioconductor-biostrings=2.70.1
 - bioconductor-factr

